title: datacur8
description: "A config-driven CLI that validates and enforces cross-file integrity for structured JSON, YAML, and CSV datasets in a repo, then can export compiled outputs and deterministically tidy files for stable diffs."

remote_theme: just-the-docs/just-the-docs@v0.12.0
plugins:
  - jekyll-remote-theme

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.12.3"

# External navigation links
nav_external_links:
  - title: datacur8 on GitHub
    url: https://github.com/UnitVectorY-Labs/datacur8

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/UnitVectorY-Labs/datacur8"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"
